const Carsdata = [
  {
    id: 5,
    Make: "Audi",
    Model: "A3",
    Price: 32450,
    Condition: "",
    Discount: "",
    Date: "2021-03-02",
  },
  {
    id: 6,
    Make: "VW",
    Model: "Golf 3",
    Price: 850,
    Condition: "Used",
    Discount: "12%",
    Date: "2021-03-05",
  },
  {
    id: 65,
    Make: "BMW",
    Model: "354i",
    Price: 8890.5,
    Condition: "Used",
    Discount: "12%",
    Date: "2007-06-21",
  },
  {
    id: 8,
    Make: "Trabant",
    Model: "3601 Deluxe54i",
    Price: 1000,
    Condition: "New",
    Discount: "",
    Date: "12/9/1989",
  },
  {
    id: 7,
    Make: "Audi",
    Model: "Van type",
    Price: 8900,
    Condition: "New",
    Discount: "n/a",
    Date: "",
  },
  {
    id: 78,
    Make: "Jaguar",
    Model: "X-Type",
    Price: 56000,
    Condition: "USED",
    Discount: "",
    Date: "12/16/2005",
  },
  {
    id: 76,
    Make: "Toyota",
    Model: "Corolla",
    Price: 18995,
    Condition: "",
    Discount: "8.5%",
    Date: "3/12/2014",
  },
  {
    id: 98,
    Make: "Toyota",
    Model: "Corolla",
    Price: 21200,
    Condition: "",
    Discount: "n/a",
    Date: "11/9/2018",
  },
  {
    id: 99,
    Make: "Toyota",
    Model: "Corolla",
    Price: 9200,
    Condition: "USED",
    Discount: "",
    Date: "9/16/2014",
  },
  {
    id: 95,
    Make: "Toyota",
    Model: "Corolla",
    Price: 9200,
    Condition: "USED",
    Discount: "",
    Date: "9/16/2014",
  },
  {
    id: 23,
    Make: "Mercedes",
    Model: "E-Class",
    Price: 9999.95,
    Condition: "USED",
    Discount: "8000",
    Date: "4/4/2021",
  },
  {
    id: 25,
    Make: "Mercedes",
    Model: "S-Class",
    Price: 12000,
    Condition: "",
    Discount: "",
    Date: "3/2/2021",
  },
  {
    id: 67,
    Make: "Ford",
    Model: "Bronco Vintage Supreme",
    Price: 8950.3,
    Condition: "USED",
    Discount: "",
    Date: "8/26/1995",
  },
  {
    id: 71,
    Make: "Mini",
    Model: "Classic Saloon",
    Price: 2999.95,
    Condition: "USED",
    Discount: "5.00%",
    Date: "8/26/1995",
  },
  {
    id: 72,
    Make: "Mini",
    Model: "Classic Saloon X3",
    Price: 2000,
    Condition: "",
    Discount: "",
    Date: "3/11/2002",
  },
  {
    id: 2,
    Make: "Mercedes",
    Model: "S-Class",
    Price: 34000,
    Condition: "NEW",
    Discount: "10%",
    Date: "3/2/2021",
  },
];

export default Carsdata;
